### PR TITLE
Fix bug in joi rendering of an object type with a discriminator.

### LINKED ISSUE #94: Generated Joi code broken for object type with discriminator
Our code generator for Joi currently doesn't generate the `.only(<discriminatorValue>)` rule correctly.
We should fix it.

### PR DESCRIPTION
**Pull request by katmatt**
This PR closes #94

### CODE REVIEW

File: languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/joi/JoiValidatorModuleRenderer.kt [hunk 1]
```diff
@@ -127,12 +128,11 @@ class JoiValidatorModuleRenderer @Inject constructor(override val vrapTypeProvid
         }
     }
 
-    fun Property.renderPropertyTypeSchema(): String {
-        val owner: ObjectType = eContainer() as ObjectType
+    fun Property.renderPropertyTypeSchema(current : ObjectType): String {
```
Comment (katmatt) [inline languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/joi/JoiValidatorModuleRenderer.kt]: Here we need to pass in for which property we render. This is because we render all properties and they have different owners.
